---
- name: install htop
  package:
          name: htop
          state: present

- name: install vim
  package:
          name: vim
          state: present

- name: install tmux
  package:
          name: tmux
          state: present
          
- name: 

